homeassistant:
  customize:
    sensor.dish_machine_status:
      icon: mdi:dishwasher

#################################################################
#                                                               #
#                            Inputs                             #
#                                                               #
#################################################################  

input_boolean:
  disable_dish_machine_notification:
    name: Disable dish Machine Notification
    initial: off
    icon: mdi:dishwasher  
    
    
input_select:
  dish_machine_status:
    name: Dish Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################  

sensor:

####################################################
#                                                  #
#                Sensors - Template                #
#                                                  #
####################################################

  - platform: template
    sensors:
## Washing Machine Status
      dish_machine_status:
        value_template: '{{ states.input_select.dish_machine_status.state}}'
        friendly_name: 'Dish Machine Status'
## Washing Machine Power Usage
      dish_machine_power:
        value_template: '{{ states.switch.oppvaskmaskin.attributes.current_power_w|int }}'  
        friendly_name: 'dish Machine Power' 