homeassistant:
  customize:
    sensor.washing_machine_status:
      icon: mdi:washing-machine



#################################################################
#                                                               #
#                            Inputs                             #
#                                                               #
#################################################################  

input_boolean:
  disable_washing_machine_notification:
    name: Disable Washing Machine Notification
    initial: off
    icon: mdi:washing-machine

  notfy_washing_machine_finished:
    name: tts Washing Machine Finished
    initial: off

  notfy_dishwasher_finished:
    name: tts Dish Washer Finished
    initial: off 
    
    
input_select:
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle


#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################  

sensor:

####################################################
#                                                  #
#                Sensors - Template                #
#                                                  #
####################################################

  - platform: template
    sensors:
## Washing Machine Status
      washing_machine_status:
        value_template: '{{ states.input_select.washing_machine_status.state}}'
        friendly_name: 'Washing Machine Status'
## Washing Machine Power Usage
      waching_machine_power:
        value_template: "{{ state_attr('switch.vaskemaskin', 'current_power_w')|int }}"
        friendly_name: 'Washing Machine Power' 