custom_header:
  kiosk_mode: true

button_card_templates:
  !include lovelace/button_card_templates/button_card_templates.yaml

decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

title: Home
background: var(--background)
views:
  - title: Nest
    icon: mdi:monitor-dashboard
    panel: true
    background: "right/auto linear-gradient(23deg, rgba(211,211,211,1) 0%, rgba(223,223,223,1) 34%, rgba(255,255,255,1) 100%)"
    path: nest-dash
    cards:
      - type: vertical-stack
        cards:
          - type: custom:nest-layout-card
            layout: horizontal
            max_width: [960px, 100%]
            column_num: 2
            max_columns: 2
            cards:
              - type: vertical-stack
                cards:
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        template: nest_picture_button
                        entity: person.kristian
                      - type: custom:button-card
                        template: nest_picture_button
                        entity: sensor.lill_venke
                      - type: custom:button-card
                        template: nest_picture_button
                        entity: sensor.jakob
                      - type: custom:button-card
                        template: nest_picture_button
                        entity: sensor.samuel
                  - type: custom:weather-card
                    entity: weather.my_home
                    style: |
                      ha-card {
                        background-color: rgba(0, 0, 0, 0);
                        -webkit-box-shadow: none;
                        -moz-box-shadow: none;
                        box-shadow: none;
                      {
                  - type: entities
                    show_header_toggle: false
                    show_icon: false
                    entities:
                      - entity: sensor.rute_first
                        name: 'Rute Første Buss'
                      - entity: sensor.next_buss_grenseveien
                        name: 'Neste Buss'
                      - entity: sensor.rute_second
                        name: 'Rute neste buss'
                      - type: 'custom:text-divider-row'
                        text: Neste Buss mot Vinterbro
                      - entity: sensor.transport_grenseveien_platform_9603
                        name: 'Første Buss'
                      - entity: sensor.rute_first_bhg
                        name: 'Rute'
                      - entity: sensor.next_buss_grenseveien_bhg
                        name: 'Neste Buss'
                      - entity: sensor.rute_second_bhg
                        name: 'Neste Buss'          
                    style: |
                      ha-card {
                        height: 300px;
                        font-family: 'Open Sans', sans-serif;
                        font-size: 20px !important;
                        margin-bottom: 5px;
                        margin-right: 5px;
                        background-color: rgba(0, 0, 0, 0);
                        -webkit-box-shadow: none;
                        -moz-box-shadow: none;
                        box-shadow: none;
                      }
##############################################################################################################
#                                  Right Side                                                                #
##############################################################################################################

              - type: "custom:atomic-calendar-revive"
                showWeekDay: true
                entities:
                  - entity: calendar.premier_league
                  - entity: calendar.kfosserud_gmail_com
                  - entity: calendar.resident_fosserud_gmail_com
                dataSize: 200
                titleSize: 250
                maxDaysToShow: 14
                showNoEventsForToday: true
                style: |
                  ha-card {
                    height: 436px;
                    font-family: 'Open Sans', sans-serif;
                    font-size: 20px !important;
                    margin-bottom: 10px;
                    margin-right: 5px;
                  }         

              
