##############################################################################
# Automations to configure slider controls on page 4 as light dimmers
automation:
  - alias: hasp_plate_soverom_p4_DimmersInit
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate_soverom_connected"
        to: "on"
      - platform: homeassistant
        event: start
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate_soverom/command/p[4].b[4].txt"
          payload: '"Soverom"'
      - service: mqtt.publish
        data:
          topic: "hasp/plate_soverom/command/p[4].b[5].txt"
          payload: '"Gang"'
      - service: mqtt.publish
        data:
          topic: "hasp/plate_soverom/command/p[4].b[6].txt"
          payload: '"Trapp"'

  # when the user moves the slider, change the light in Hass
  - alias: hasp_plate_soverom_p4_Dimmer7UpdateHass
    trigger:
      - platform: mqtt
        topic: "hasp/plate_soverom/state/p[4].b[7].val"
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.hovedsoverom
          brightness: "{{ trigger.payload }}"

  # When the light is changed in Hass, update HASP to move the dimmer
  - alias: hasp_plate_soverom_p4_Dimmer7UpdateHASP
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate_soverom_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: light.hovedsoverom
    action:
      - service: mqtt.publish
        data_template:
          topic: "hasp/plate_soverom/command/p[4].b[7].val"
          payload_template: "{{states.light.hovedsoverom.attributes.brightness|default(0)|int}}"

  # when the user moves the slider, change the light in Hass
  - alias: hasp_plate_soverom_p4_Dimmer8UpdateHass
    trigger:
      - platform: mqtt
        topic: "hasp/plate_soverom/state/p[4].b[8].val"
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.gang_soverom_2
          brightness: "{{ trigger.payload }}"

  # When the light is changed in Hass, update HASP to move the dimmer
  - alias: hasp_plate_soverom_p4_Dimmer8UpdateHASP
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate_soverom_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: light.gang_soverom_2
    action:
      - service: mqtt.publish
        data_template:
          topic: "hasp/plate_soverom/command/p[4].b[8].val"
          payload_template: "{{states.light.gang_soverom_2.attributes.brightness|default(0)|int}}"

  # when the user moves the slider, change the light in Hass
  - alias: hasp_plate_soverom_p4_Dimmer9UpdateHass
    trigger:
      - platform: mqtt
        topic: "hasp/plate_soverom/state/p[4].b[9].val"
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.lys_gang_2_etg_2
          brightness: "{{ trigger.payload }}"

  # When the light is changed in Hass, update HASP to move the dimmer
  - alias: hasp_plate_soverom_p4_Dimmer9UpdateHASP
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate_soverom_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: light.lys_gang_2_etg_2
    action:
      - service: mqtt.publish
        data_template:
          topic: "hasp/plate_soverom/command/p[4].b[9].val"
          payload_template: "{{states.light.lys_gang_2_etg_2.attributes.brightness|default(0)|int}}"

##############################################################################
# Automations to set colors on HASP Page 4
#
# Here we've swapped selected/unselected as these buttons will always be
# unselected (unless actively being pressed), and sliders do not have a
# selected/unselected state.
  - alias: hasp_plate_soverom_p4_ColorConfig_selectedforegroundcolor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate_soverom_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_plate_soverom_selectedforegroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate_soverom/command/json"
          payload_template: >-
            [{%- for i in range(4,7) -%}"p[4].b[{{i}}].pco={{ states('input_number.hasp_plate_soverom_selectedforegroundcolor')|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]

  - alias: hasp_plate_soverom_p4_ColorConfig_selectedbackgroundcolor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate_soverom_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_plate_soverom_selectedbackgroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate_soverom/command/json"
          payload_template: >-
            [{%- for i in range(4,7) -%}"p[4].b[{{i}}].bco={{ states('input_number.hasp_plate_soverom_selectedbackgroundcolor')|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]

  - alias: hasp_plate_soverom_p4_ColorConfig_unselectedforegroundcolor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate_soverom_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_plate_soverom_unselectedforegroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate_soverom/command/json"
          payload_template: >-
            [{%- for i in range(4,7) -%}"p[4].b[{{i}}].pco2={{ states('input_number.hasp_plate_soverom_unselectedforegroundcolor')|int }}",{%- endfor -%}
            {%- for i in range(7,10) -%}"p[4].b[{{i}}].pco={{ states('input_number.hasp_plate_soverom_unselectedforegroundcolor')|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]

  - alias: hasp_plate_soverom_p4_ColorConfig_unselectedbackgroundcolor
    trigger:
      - platform: state
        entity_id: "binary_sensor.plate_soverom_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_plate_soverom_unselectedbackgroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/plate_soverom/command/json"
          payload_template: >-
            [{%- for i in range(4,7) -%}"p[4].b[{{i}}].bco2={{ states('input_number.hasp_plate_soverom_unselectedbackgroundcolor')|int }}",{%- endfor -%}
            {%- for i in range(7,10) -%}"p[4].b[{{i}}].bco={{ states('input_number.hasp_plate_soverom_unselectedbackgroundcolor')|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]
