#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    switch.roomba:
      icon: mdi:robot-vacuum
    sensor.roomba:
      icon: mdi:robot-vacuum
    sensor.roomba_battery:
      icon: mdi:battery
      unit_of_measurement: '%'
    sensor.roomba_status:
      icon: mdi:robot-vacuum



switch:
#Roomba Switch
  - platform: mqtt
    name: "Roomba"
    command_topic: "roomba/commands"
    payload_on: "start"
    payload_off: "stop"  
sensor:
#Roomba Sensors
  - platform: mqtt
    name: "Roomba Status"
    state_topic: "roomba/currentStatus"
  - platform: mqtt
    name: "Roomba Battery"
    state_topic: "roomba/battery"