#################################################################
#                                                               #
#                       Device Tracker                          #
#                                                               #
#################################################################

device_tracker:

####################################################
#                                                  #
#               Device Track - Ping                #
#                                                  #
####################################################

  - platform: ping
    hosts:
      core_router: 192.168.86.1
      soverom_ap: 192.168.86.39
      telldus_bridge: 192.168.86.249
      3d_printer: 192.168.86.24
      broadlink_rm_soverom: 192.168.86.33
      broadlink_ir_stue: 192.168.86.30


sensor:
  - platform: google_wifi
    host: !secret router
    name: core_router

  - platform: template
    sensors:
      sonoff_rf_bridge_state:
        friendly_name: sonoff rf bridge status
        entity_id: binary_sensor.sonoff_rf_bridge_status
        value_template: >-
          {% if is_state('binary_sensor.sonoff_rf_bridge_status', 'on') %}
            100
          {% elif is_state('binary_sensor.sonoff_rf_bridge_status', 'off') %}
            0
          {% endif %}

      telldus_bridge_state:
        friendly_name: telldus bridge status
        entity_id: binary_sensor.sonoff_rf_bridge_status
        value_template: >-
          {% if is_state('binary_sensor.telldus_bridge', 'on') %}
            100
          {% elif is_state('binary_sensor.telldus_bridge', 'off') %}
            0
          {% endif %}

      3d_printer_state:
        friendly_name: 3d printer status
        entity_id: binary_sensor.3d_printer
        value_template: >-
          {% if is_state('binary_sensor.3d_printer', 'on') %}
            100
          {% elif is_state('binary_sensor.3d_printer', 'off') %}
            0
          {% endif %}

      broadlink_rm_soverom_state:
        friendly_name: Broadlink RM Soverom
        entity_id: binary_sensor.broadlink_rm_soverom
        value_template: >-
          {% if is_state('binary_sensor.broadlink_rm_soverom', 'on') %}
            100
          {% elif is_state('binary_sensor.broadlink_rm_soverom', 'off') %}
            0
          {% endif %}

      broadlink_ir_stue_state:
        friendly_name: Broadlink IR stue
        entity_id: binary_sensor.broadlink_ir_stue
        value_template: >-
          {% if is_state('binary_sensor.broadlink_ir_stue', 'on') %}
            100
          {% elif is_state('binary_sensor.broadlink_ir_stue', 'off') %}
            0
          {% endif %}


#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:

  internet:
    name: Internet
    entities:
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload


#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensor - Template              #
#                                                  #
####################################################

  - platform: template
    sensors:
      core_router:
        friendly_name: Core Router
        device_class: connectivity
        entity_id: device_tracker.core_router
        value_template: "{{ is_state('device_tracker.core_router', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.core_router', 'home') %}
            mdi:router-wireless
          {% else %}
            mdi:router-wireless
          {% endif %}

      telldus_bridge:
        friendly_name: telldus_bridge
        device_class: connectivity
        entity_id: device_tracker.telldus_bridge
        value_template: "{{ is_state('device_tracker.telldus_bridge', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.telldus_bridge', 'home') %}
            mdi:checkbox-blank-circle-outline
          {% else %}
            mdi:checkbox-blank-circle-outline
          {% endif %}

      3d_printer:
        friendly_name: 3d Printer
        device_class: connectivity
        entity_id: device_tracker.3d_printer
        value_template: "{{ is_state('device_tracker.3d_printer', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.3d_printer', 'home') %}
            mdi:printer-3d
          {% else %}
            mdi:printer-3d
          {% endif %}

      broadlink_rm_soverom:
        friendly_name: Broadlink rm Soverom
        device_class: connectivity
        entity_id: device_tracker.broadlink_rm_soverom
        value_template: "{{ is_state('device_tracker.broadlink_rm_soverom', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.broadlink_rm_soverom', 'home') %}
            mdi:access-point-network
          {% else %}
            mdi:access-point-network
          {% endif %}

      broadlink_ir_stue:
        friendly_name: Broadlink ir Stue
        device_class: connectivity
        entity_id: device_tracker.broadlink_ir_stue
        value_template: "{{ is_state('device_tracker.broadlink_ir_stue', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.broadlink_ir_stue', 'home') %}
            mdi:access-point-network
          {% else %}
            mdi:access-point-network
          {% endif %}


#################################################################
#                                                               #
#                          Speed Test                           #
#                                                               #
################################################################# 
  
speedtestdotnet:
  server_id: 14444
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

